### ISSUE TITLE
Getting Error Adding Data Source error with Docker

### ISSUE THREAD

**Issue by rakeshnemade** [babelouest/taliesin#4]
I am getting "Error Adding Data Source" message when adding a datasource with the following docker image on Mac babelouest/taliesin_x86_64_sqlite_noauth_quickstart.

**Comment by babelouest** [comment]
Hello @rakeshnemade ,

It may be not clear in the [docker page](https://hub.docker.com/r/babelouest/taliesin_x86_64_sqlite_noauth_quickstart). Instead of mounting the folder `/media/Music/`, you should mount the volume the path to your media folder.
Then, you must use `/media/` or a subfolder as the value for `Path on server` in the `Add new Data Source` modal.

For example, change the values `MEDIA_FOLDER` and `DATABASE_PATH` accordingly:

```shell
$ export MEDIA_FOLDER=/media/Music
$ export DATABASE_PATH=/tmp/taliesin/
$ docker run --rm -it -p 8576:8576 -v $DATABASE_PATH:/var/cache/taliesin -v $MEDIA_FOLDER:/media babelouest/taliesin_x86_64_sqlite_noauth_quickstart
```

**Comment by rakeshnemade** [comment]
Thanks Nicolas , I was able to get it run.
